### ISSUE TITLE
please   update   flutter_translate_app 

### ISSUE THREAD

**Issue by kalimaty** [camilo1498/flutter_translate_app#1]
please   update   flutter_translate_app 
for  latest  versions  flutter
and  also  pachages

![8000](https://github.com/camilo1498/flutter_translate_app/assets/105967966/7a145a35-8b3f-46f0-9eef-84a608c5919a)

**Comment by camilo1498** [comment]
Hi @kalimaty!, the app is already updated, please check the repo again

**Comment by kalimaty** [comment]
but the  translation not  not working  
please check it  agian
